<?php

namespace Ordermind\LogicalAuthorizationBundle\Tests\ODM\Fixtures\Repository\Annotation;

/**
 * TestDocumentNoBypassRepository
 *
 * This class was generated by the Doctrine ODM. Add your own custom
 * repository methods below.
 */
class TestDocumentNoBypassRepository extends \Doctrine\ODM\DocumentRepository
{
  public function customMethod() {
    return $this->findAll();
  }
}
