# Register classes from the Logical Permissions library as services

services:
    logical_permissions.permission_checker_locator:
        class: Ordermind\LogicalPermissions\PermissionCheckerLocator
        arguments: [!tagged logauth.tag.permission_checker]
        public: false

    logical_permissions.facade:
        class: Ordermind\LogicalPermissions\LogicalPermissionsFacade
        arguments: ['@logical_permissions.permission_checker_locator', '@logauth.bypass_access_checker']
        public: false