# Permission checkers

services:
    logauth.permission_checker.simple_condition:
        class: Ordermind\LogicalAuthorizationBundle\PermissionCheckers\SimpleConditionChecker\SimpleConditionCheckerManager
        arguments: [!tagged_iterator logauth.tag.permission_checker.simple_condition]
        tags:
            - {name: logauth.tag.permission_checker}
        public: false

    logauth.permission_checker.simple_condition.user_can_bypass_access:
        class: Ordermind\LogicalAuthorizationBundle\PermissionCheckers\SimpleConditionChecker\Checkers\UserCanBypassAccessChecker
        tags:
            - {name: logauth.tag.permission_checker.simple_condition}
        public: false

    logauth.permission_checker.simple_condition.user_has_account:
        class: Ordermind\LogicalAuthorizationBundle\PermissionCheckers\SimpleConditionChecker\Checkers\UserHasAccountChecker
        tags:
            - {name: logauth.tag.permission_checker.simple_condition}
        public: false

    logauth.permission_checker.simple_condition.user_is_author:
        class: Ordermind\LogicalAuthorizationBundle\PermissionCheckers\SimpleConditionChecker\Checkers\UserIsAuthorChecker
        tags:
            - {name: logauth.tag.permission_checker.simple_condition}
        public: false

    logauth.permission_checker.role:
        class: Ordermind\LogicalAuthorizationBundle\PermissionCheckers\RoleChecker
        arguments: ['@security.role_hierarchy']
        tags:
            - {name: logauth.tag.permission_checker}
        public: false

    logauth.permission_checker.host:
        class: Ordermind\LogicalAuthorizationBundle\PermissionCheckers\HostChecker
        arguments: ['@request_stack']
        tags:
            - {name: logauth.tag.permission_checker}
        public: false

    logauth.permission_checker.method:
        class: Ordermind\LogicalAuthorizationBundle\PermissionCheckers\MethodChecker
        arguments: ['@request_stack']
        tags:
            - {name: logauth.tag.permission_checker}
        public: false

    logauth.permission_checker.ip:
        class: Ordermind\LogicalAuthorizationBundle\PermissionCheckers\IpChecker
        arguments: ['@request_stack']
        tags:
            - {name: logauth.tag.permission_checker}
        public: false