services:
  ordermind_logical_authorization.debug.tree_collector:
    class: Ordermind\LogicalAuthorizationBundle\DataCollector\TreeCollector
    arguments: ['@ordermind_logical_authorization.service.permission_tree_builder']
    tags:
      {name: data_collector, template: OrdermindLogicalAuthorizationBundle:data_collector:tree_collector, id: logauth.tree_collector}
    public: false
