services:
  logauth.debug.tree_collector:
    class: Ordermind\LogicalAuthorizationBundle\DataCollector\TreeCollector
    arguments: ['@logauth.service.permission_tree_builder']
    tags:
      - {name: data_collector, template: '@OrdermindLogicalAuthorization/DataCollector/tree_collector.html.twig', id: logauth.tree_collector}
    public: false
