# Services used only in debug mode

services:
    logauth.command.dump_permissions:
        class: Ordermind\LogicalAuthorizationBundle\Command\DumpPermissionTreeCommand
        arguments: ['@logauth.service.permission_tree_builder']
        tags:
            - {name: console.command}

    logauth.debug.collector:
        class: Ordermind\LogicalAuthorizationBundle\DebugDataCollector\Collector
        arguments: 
            - '@logauth.service.permission_tree_builder'
            - '@logical_permissions.facade'
            - '@logical_permissions.permission_checker_locator'
            - '@logauth.debug.log_items_reader'
        tags:
            -   
                name: data_collector
                template: '@OrdermindLogicalAuthorization/DebugDataCollector/collector.html.twig'
                id: logauth.collector
        public: false

    logauth.debug.log_item_collection_repository:
        class: Ordermind\LogicalAuthorizationBundle\DebugDataCollector\LogItemCollectionRepository
        public: false

    logauth.debug.log_items_reader:
        class: Ordermind\LogicalAuthorizationBundle\DebugDataCollector\LogItemsReader
        arguments: ['@logauth.debug.log_item_collection_repository']
        public: false

    logauth.debug.log_items_writer:
        class: Ordermind\LogicalAuthorizationBundle\DebugDataCollector\LogItemsWriter
        arguments: ['@logauth.debug.log_item_collection_repository']
        public: false

    logauth.debug.backtrace_factory:
        class: Ordermind\LogicalAuthorizationBundle\DebugDataCollector\BackTraceFactory
        public: false
