# Services used only in debug mode

services:
    logauth.command.dump_permissions:
        class: Ordermind\LogicalAuthorizationBundle\Command\DumpPermissionTreeCommand
        arguments: ['@logauth.service.permission_tree_builder']
        tags:
            - {name: console.command}

    logauth.debug.collector:
        class: Ordermind\LogicalAuthorizationBundle\DataCollector\Collector
        arguments: 
            - '@logauth.service.permission_tree_builder'
            - '@logical_permissions.facade'
            - '@logical_permissions.permission_checker_locator'
        tags:
            - {name: data_collector, template: '@OrdermindLogicalAuthorization/DataCollector/collector.html.twig', id: logauth.collector}
        public: false
