<?php

namespace Ordermind\LogicalAuthorizationBundle\Services;

use Ordermind\DoctrineDecoratorBundle\Services\Decorator\RepositoryDecoratorInterface as RepositoryDecoratorInterfaceBase;

interface RepositoryDecoratorInterface extends RepositoryDecoratorInterfaceBase {}
