<?php

namespace Ordermind\LogicalAuthorizationBundle\Tests\Misc\Fixtures\Repository;

/**
 * ForbiddenEntityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ForbiddenEntityRepository extends \Doctrine\ORM\EntityRepository
{
  public function customMethod() {
    return $this->findAll();
  }
}
