<?php

namespace Ordermind\LogicalAuthorizationBundle\Tests\Fixtures\Repository;

/**
 * TestEntityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TestEntityRepository extends \Doctrine\ORM\EntityRepository
{
  public function customMethod() {
    return $this->findAll();
  }
}
