<?php

namespace Ordermind\LogicalAuthorizationBundle\Tests\ODM\Fixtures\Repository\XML;

/**
 * TestDocumentVariousPermissionsRepository
 *
 * This class was generated by the Doctrine ODM. Add your own custom
 * repository methods below.
 */
class TestDocumentVariousPermissionsRepository extends \Doctrine\ODM\MongoDB\DocumentRepository
{
  public function customMethod() {
    return $this->findAll();
  }
}
