<?php

namespace Ordermind\LogicalAuthorizationBundle\Tests\ORM\Fixtures\Repository\Annotation;

/**
 * TestUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TestUserRepository extends \Doctrine\ORM\EntityRepository
{
}
