<?php

namespace Ordermind\LogicalAuthorizationBundle\Tests\ODM\Fixtures\Repository;

/**
 * TestUserRepository
 *
 * This class was generated by the Doctrine ODM. Add your own custom
 * repository methods below.
 */
class TestUserRepository extends \Doctrine\ODM\MongoDB\DocumentRepository
{
}
