<?php

namespace Ordermind\LogicalAuthorizationBundle\Tests\ORM\Fixtures\Repository\YML;

/**
 * TestEntityOverriddenPermissionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TestEntityOverriddenPermissionsRepository extends \Doctrine\ORM\EntityRepository
{
  public function customMethod() {
    return $this->findAll();
  }
}
